OffchainLabs/arbitrum-sdk

package.json
src/lib/message/L2ToL1Message.ts
yarn.lock

Added a utility method to calculate node deadline following the implementation from the [token bridge]( https://github.com/OffchainLabs/arb-token-bridge/blob/02817aff63b87f7a6dabe5fa4f6457fc024460a9/packages/token-bridge-sdk/src/hooks/useArbTokenBridge.ts#L1052) and substituting [subgraphs](https://github.com/OffchainLabs/arbitrum-subgraphs/blob/e6be72526329c5a8e04b39393a258e39c5c49363/packages/arb-bridge-eth/src/mapping.ts#L200-L210) for event queries

Add node deadline estimation for L2 to L1 messages

---

package.json
src/lib/message/L1ToL2MessageGasEstimator.ts

Temporary workaround of incorrect gas estimation. Also see https://github.com/OffchainLabs/arb-token-bridge/pull/303

fix: default l2 gas buffer

---

README.md
integration_test/eth.test.ts
package.json
src/lib/message/L1Transaction.ts
src/lib/utils/migration_types.ts

Update the l1 transaction receipt for eth deposits to follow the nitro format

fix: Nitro deposit format

---

.npmrc
package.json

the version bump from https://github.com/OffchainLabs/arbitrum-sdk/pull/66 wasn't published yet, so we can have it as part of the same patch release

chore: contract packages as dev dependencies, add prepare script

---

package.json
src/lib/assetBridger/erc20Bridger.ts
src/lib/dataEntities/errors.ts
src/lib/message/L2ToL1Message.ts

We make the l1provider optional so as not to break the api

fix: validate l1 address before returning

---

package.json

We only use this for hardhat, which we only use in builds which dont make http requests

fix: Updated audit to include undici vuln

---

package.json
src/lib/assetBridger/erc20Bridger.ts

For token without .l1Address() (e.g. DAI), `getL1ERC20Address` will throw with CALL_EXCEPTION
https://github.com/OffchainLabs/arbitrum-sdk/blob/afd58837a06f4e061b8f56f26db14e50439c7d7b/src/lib/assetBridger/erc20Bridger.ts#L355-362
```solidity
public async getL1ERC20Address(
erc20L2Address: string,
l2Provider: Provider
): Promise<string> {
await this.checkL2Network(l2Provider)
const arbERC20 = L2GatewayToken__factory.connect(erc20L2Address, l2Provider)
const l1Address = await arbERC20.functions.l1Address().then(([res]) => res)
```
There doesn't seems to be any on-chain registry that can resolve a L2 -> L1 address mapping. Another question is do we want to special case DAI by hardcoding the address here (but still do the validation to make it less risky).
Also added a validation fallback in …

fix: improve getL1ERC20Address error message

---

package.json
src/lib/message/L1ToL2Message.ts
src/lib/message/L1Transaction.ts
yarn.lock

adds support for changes in https://github.com/OffchainLabs/go-ethereum/pull/112
also adds a `status` function you can query on eth deposits

feat: add support for new eth deposit msg and include status function

---

package.json
src/lib/inbox/inbox.ts
src/lib/message/L1ToL2Message.ts
src/lib/message/L2ToL1Message.ts
src/lib/utils/lib.ts
yarn.lock

Cherry picked commits from https://github.com/OffchainLabs/arbitrum-sdk/pull/98
Changed the base of that PR which made stuff messy
Should still address https://github.com/OffchainLabs/arbitrum-sdk/pull/98#discussion_r907216098

fix: hotfixes for nitro support

---

src/lib/message/L1ToL2Message.ts

Throw as described in spec, also if we don't throw here we will call `getSuccessfulRedeem` which will then call `getRetryableCreationReceipt` with default timeout (15m).

Throw on waitForStatus timeout

---

package.json
src/lib/dataEntities/networks.ts

Mostly the same as https://github.com/OffchainLabs/arbitrum-sdk/pull/123, except the numbers have changed.
[1081677](https://github.com/advisories/GHSA-3cvr-822r-rqcc) 
[1081921](https://github.com/advisories/GHSA-q768-x9m6-m9qp)
[1081848](https://github.com/advisories/GHSA-pgw7-wx7w-2w33)
Undici, hardhat build stuff, we only use this in dev, and even there we only use local stuff so undici is never called
[1081989](https://github.com/advisories/GHSA-qh9x-gcfh-pcrw)
[1081990](https://github.com/advisories/GHSA-qh9x-gcfh-pcrw)
[1083165](https://github.com/advisories/GHSA-7grf-83vw-6f5x)
[1083163](https://github.com/advisories/GHSA-7grf-83vw-6f5x)
OZ ERC165 - not used by us
[1081919](https://github.com/advisories/GHSA-4g63-c64m-25w9) …

Updated the audit list

---

src/lib/dataEntities/networks.ts

This is only a problem with the migration package, where isNitroL2 needs to get l1 rpc url, so we put onto the network object with an env var

Populate the l1rpc if it isnt populated already, used in the tutorials

---

package.json
src/lib/utils/migration_types.ts

Tried to use `getL1Network` instead of `nitro.getL1Network` but for the use case in `isNitroL2` we only have the l2 chainid and don't have the l2 provider yet, which is not supported by `getL1Network` since it require a provider.

Use envvar L1RPC in isNitro checks

---

README.md
scripts/testSetup.ts
src/lib/dataEntities/networks.ts

Attach the `isArbitrum: false` property to L1 networks.
This will make it nicer to work with cases where your type is `L1Network | L2Network` and you need to check if it’s Arbitrum (without checking the id).

Enhancement (V3) : Attach the ”isArbitrum: false"  property to L1 networks

---

package.json

the package didn't need to be bumped in https://github.com/OffchainLabs/arbitrum-sdk/pull/180/commits/834a3d4e7fa672caa4e0eb2afd540cd68bf24939 since the previous version had not been published

chore: undo package bump

---

scripts/lib.ts
src/lib/message/L1Transaction.ts

`getL1ToL2Messages` did not check if the bridgeMessageEvent is from the inbox matching the supplied l2provider. 
https://github.com/OffchainLabs/arbitrum-sdk/blob/f6f4c5862baaa6c7537ece45e26d0d7d10d2ff3c/src/lib/message/L1Transaction.ts#L215-L221
If the same L1 tx send to both arb1 and nova some invalid retryable will show up. i.e.
1. nova data with nova chainid
2. arb1 data with nova chainid (invalid)
3. arb1 data with arb1 chainid
4. nova data with arb1 chainid (invalid)
e.g.
https://retryable-dashboard.arbitrum.io/?t=0xc69036ab70acdd288f6db6aff67b6ac1a3f92cfc855d93b5629e1a0ee8f28cbc

fix: check inbox of bridgeMessageEvent

---

src/index.ts
src/lib/message/L1ToL2Message.ts

In v3.0.0-rc.1, we used L1ToL2MessageStatus for ETH deposits which doesn't makes sense for "NOT_YET_CREATED" status. In this PR we added EthDepositStatus that represents status for ETH deposits.

adding EthDepositStatus

---

integration_test/eth.test.ts
integration_test/testHelpers.ts
package.json
src/lib/assetBridger/erc20Bridger.ts
src/lib/assetBridger/ethBridger.ts
src/lib/dataEntities/transactionRequest.ts

We do this so that the request returned can be passed directly into estimateGas

feat: Added 'from' address to eth and erc20 withdrawal requests

---

src/lib/message/L1ToL2MessageCreator.ts
tests/integration/l1ToL2MessageCreator.test.ts

Method `L1ToL2MessageCreator.createRetryableTicket` breaks as SendTransaction is expecting a TransactionRequest object, but it's receiving the full object created by `getTicketCreationRequest`. 
Also added some tests for this method.

fix: properly create retryable ticket via tx request

---

src/lib/assetBridger/ethBridger.ts
tests/integration/eth.test.ts

New `ethBridger.depositTo` method that allows a user to deposit ETH to a different address on L2 by using a Retryable Ticket.
There are different ways to implement the function, but I've prioritized having a simpler function body and just using the parameters to create the retryable ticket (instead of having a more similar function signature to that of `deposit()` and a slightly more complex body).
Added also a test to `eth.test.ts`.
Closes https://github.com/OffchainLabs/arbitrum-sdk/issues/219.

feat: add method for depositing eth to a different address

---

src/index.ts

Updated export to be consistent. They can now both be imported through `import { L1ToL2MessageReader, L1ToL2MessageReaderClassic } from '@arbitrum/sdk';`

Update export for consistency

---

package.json
src/lib/message/L1ToL2Message.ts

When retryTo is set to 0x0, ArbOS treat it as nil and do contract deployment instead of sending to address(0)
https://github.com/OffchainLabs/go-ethereum/blob/01cc043469b25ca03a296be256aae2082c161bd7/core/types/arb_types.go#L50
This lead to a bug in how the sdk calculate retryableid when retryTo is 0x0
Example:
L1 Tx: https://etherscan.io/tx/0xbe273cc350c0e4f3350cd7a2a63d802ad9cf071b1f724e60dfb3d5b374604878
RetryableId before fix: [0x7bd9445851a206f6f30a610797bc88d8fbad19581023996a9030977a1bd77722](https://retryable-dashboard.arbitrum.io/tx/0xbe273cc350c0e4f3350cd7a2a63d802ad9cf071b1f724e60dfb3d5b374604878)
RetryableId after fix: [0x89d991be089b33e98f4a3aa5e4bc87f22e45e28a943e09bec929ec27119f5492](https://arbiscan.io/tx/0x89d991be089b33e98f4a3aa5e4bc87f22e45e28a943e09bec929ec27119f5492)

fix: retryable rlp when destAddress is 0x0

---

src/lib/dataEntities/networks.ts

Increased to 30 minutes in both One and Nova
2 epochs => ~13 minutes
Time to create and redeem the ticket => ~10 minutes
Extra buffer of time => ~7 minutes

Increase default timeout for the creation and redemption of retryable tickets

---

audit-ci.jsonc

OpenZeppelin Contracts TransparentUpgradeableProxy clashing selector calls may not be delegated
https://github.com/advisories/GHSA-mx2q-35m2-x2rh
from: @openzeppelin/contracts AND @openzeppelin/contracts-upgradeable
Reason: Clashing selector between proxy and implementation can only be caused deliberately
GovernorCompatibilityBravo may trim proposal calldata
https://github.com/advisories/GHSA-93hq-5wgc-jc82
from: @openzeppelin/contracts AND @openzeppelin/contracts-upgradeable
Reason: We don't use GovernorCompatibilityBravo

Added more allowed vulnerabilities

---

src/lib/message/L1ToL2Message.ts

ensure errors that aren't call reverts (i.e., RPC timeout errors) just throw / don't cause retryableExists to return false (which can lead to `status()` incorrectly reporting "expired"

Fix retryableExists

---

src/lib/message/L2ToL1Message.ts
src/lib/message/L2ToL1MessageClassic.ts
src/lib/message/L2ToL1MessageNitro.ts

Closes https://github.com/OffchainLabs/arbitrum-sdk/issues/286.
This PR is additive only. It adds an optional `l1Provider` param when instantiating message writers, allowing you to override the L1 provider which is set by default as `l1Signer.provider`.
Reason behind the change was that in the Bridge UI, a particular version bump of `wagmi` changed the shape of the provider that's attached to the signer for some wallets, and some static calls were failing. Allowing us to pass in a provider of our own gives us more control.

feat: override L1 Provider in `L2ToL1MessageWriter`

---

scripts/sendL2SignedMsg.ts
src/lib/inbox/inbox.ts
tests/integration/sendL2msg.test.ts

chore: rename L1 and L2 to parent and child chain in inbox

---

src/lib/message/L2ToL1MessageNitro.ts

Fixes an issue with newly deployed Orbit chains when there are no assertions yet. In that case, we return block 0.

fix: default block to 0 if no NodeCreated events found

---

.github/workflows/build-test.yml

a change in the `nitro-testnode` repo has broken tests here. 
We should probably rely on the `release` branch for testing here so changes to `nitro-testnode` that aren't released don't break our builds.

chore: update testnode version

---

scripts/testSetup.ts
src/index.ts
src/lib/dataEntities/networks.ts
tests/unit/network.test.ts

- Renamed `addCustomNetwork` to `registerCustomArbitrumNetwork` because I feel that's the language everyone uses anyway when talking about custom networks in the SDK
- Added back the check for `isCustom`
- The function no longer throws if a network is already registered, but you can make it do so with `options.throwIfAlreadyRegistered`
- The function now returns the registered network because it's convenient

feat: update behaviour for registering custom networks

---

src/lib/assetBridger/erc20Bridger.ts

Small fix. 
`L2GatewayRouter__factory` needs to be used instead of `L1GatewayRouter__factory`  in `getL2GatewaySetEvents`.

fix: use L2GatewayRouter abi

---

audit-ci.jsonc
package.json
yarn.lock

- Bump ws versions
- Add GHSA-3787-6prv-h9w3 to ignored audit error

fix: bump new advisory ws to patched version

---

src/index.ts
src/lib/dataEntities/networks.ts

The testnode changes too frequently for us to have a util

feat: remove addDefaultLocalNetwork

---

audit-ci.jsonc
package.json
tests/integration/eth.test.ts
yarn.lock

Vulnerable advisories are:
https://github.com/advisories/GHSA-434g-2637-qmqr
https://github.com/advisories/GHSA-8hc4-vh64-cxmj
https://github.com/advisories/GHSA-952p-6rrq-rcjv
https://github.com/advisories/GHSA-pxg6-pf52-xh8x

ci: fix audit

---

.github/workflows/build-test.yml

Same as https://github.com/OffchainLabs/arbitrum-sdk/pull/524 but for v3. The reason we didn't have an issue already is because we didn't change dependencies, so we'd always hit the cache.

ci: replace restore action with install action

---

docs/1-introduction.mdx
docs/2-migrate.mdx

This PR fixes a few broken links on `./docs/1-introduction.md` and `./docs/2-migrate.mdx` that impact the SDK's generated docs on arbitrum-docs.

Docs: link fixes

---

.github/workflows/build-test.yml

v3 will be completely deprecated soon so we have to bump it to v4 for actions to run
see nitro's actions failed for this reason just now:
https://github.com/OffchainLabs/nitro/actions/runs/12812191448/job/35723267943?pr=2561
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

ci: bump upload artifact action version

---

audit-ci.jsonc
package.json
yarn.lock

bumping hardhat fixes this one:
`GHSA-xq7p-g2vc-g82p|hardhat>@nomicfoundation/ethereumjs-util>ethereum-cryptography>bs58check>bs58>base-x`

build(deps): bump hardhat and ignore two advisories
