- package.json
- scripts/genAbi.js
- src/lib/inbox/inbox.ts
- src/lib/message/L2ToL1Message.ts
- src/lib/utils/arbProvider.ts
- yarn.lock
This adds typechain generation for nitro contracts (rollup and precompiles)
> Add nitro typechain gen

- package.json
Added engine to be yarn v1 and Node LTS or later
> Add engine versions to package

- package.json
- src/lib/assetBridger/ethBridger.ts
- src/lib/dataEntities/errors.ts
fixes https://github.com/OffchainLabs/arbitrum/pull/2262
> fix: throw error if deposit eth will fail

- src/lib/utils/migration_types.ts
Temporary class to be used in the migration and dropped later in favour of native support on the bridgers.
> feat: Added temp easy estimates class

- integration_test/standarderc20.test.ts
- package.json
- src/lib/utils/arbProvider.ts
https://github.com/OffchainLabs/arb-token-bridge/pull/335
https://deploy-preview-335--pensive-meitner-298020.netlify.app/
> Make ArbitrumProvider support EIP 1193 providers

- package.json
to get https://github.com/OffchainLabs/arbitrum-sdk/commit/6a617e6d13e225e335671cd60514b1afada1ab26 into migration branch
> bump c-nitro-stable beta version

- src/lib/message/L2ToL1Message.ts
Calling L2ToL1Message.status() is still slow because `getSendProps` took 15s on my network for an unconfirmed message.
https://github.com/OffchainLabs/arbitrum-sdk/blob/105bf73cb788231b6e63c510713f460b36699fcd/src/lib/message/L2ToL1Message.ts#L216
Also can we narrow down the range of node to search before doing binary search? I guess we can binary search the L1 get log instead.
> Binary search in getFirstExecutableBlock

- src/lib/message/L2ToL1Message.ts
> Network generation in L2ToL1Message

- .clabot
- typedoc.js
> Add .clabot to c-nitro-migration

- integration_test/standarderc20.test.ts
- integration_test/testHelpers.ts
- src/lib/message/L1ToL2Message.ts
This is just a merge PR - updating changes from stable to nitro
> chore: Merge from stable

- scripts/testSetup.ts
Fixes https://github.com/OffchainLabs/arbitrum-sdk/issues/188
> fix: docker container name

- scripts/lib.ts
- src/lib/message/L1Transaction.ts
Cherry pick back to stable
* fix: check inbox of bridge message event
* fix: checkRetryableStatus to loop through each msg
* fix: compare lower case
> fix: Cherry pick - check inbox of bridgeMessageEvent (#198)

- package.json
- src/index.ts
for access to the aliasing utils :)
> Export Address

- audit-ci.jsonc
> ci: add new advisory to audit-ci

- audit-ci.jsonc
https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fixes failing audit
> fix: add allowed vulnerability

- src/index.ts
> chore: export ArbitrumProvider

- audit-ci.jsonc
issue only affects libraries used in dev
> chore: update advisories allowlist

- yarn.lock
fixes https://github.com/advisories/GHSA-3787-6prv-h9w3
> build: bump undici

- audit-ci.jsonc
- fixes audit failure
- updates testnode from `master` => `release`
> chore: merge main into v4

- src/lib/message/L1ToL2MessageGasEstimator.ts
- tests/integration/L1ToL2MessageGasEstimator.test.ts
> chore: renames L1ToL2MessageGasEstimator to Parent/Child 

- src/lib/message/L2Transaction.ts
- tests/integration/custom-fee-token/customFeeTokenEthBridger.test.ts
- tests/integration/eth.test.ts
- tests/integration/testHelpers.ts
> chore: rename L2Transaction to parent/child

- src/index.ts
- src/lib/assetBridger/erc20Bridger.ts
- src/lib/assetBridger/ethBridger.ts
- src/lib/message/L1ToL2MessageGasEstimator.ts
- src/lib/utils/lib.ts
- tests/integration/eth.test.ts
- tests/integration/retryableData.test.ts
- tests/integration/testHelpers.ts
- tests/unit/nativeToken.test.ts
Rename `scaleToNativeTokenDecimals` to `scaleFrom18DecimalsToNativeTokenDecimals`
Rename `nativeTokenDecimalsTo18Decimals` to `scaleFromNativeTokenDecimalsTo18Decimals`
> feat: rename decimal utilities
